import { collection, getDocs, addDoc } from 'firebase/firestore';
import { db } from './firebase';
import { Post } from './types';
import { handleFirestoreError, OperationType } from './lib/firestore-errors';

const INITIAL_POSTS: Omit<Post, 'id'>[] = [
  {
    title: "The Architecture of Transformer Models: A Deep Dive",
    slug: "architecture-of-transformer-models",
    summary: "Exploring the self-attention mechanism and why it revolutionized natural language processing.",
    content: `
# The Transformer Revolution

Transformers have changed everything in AI. From GPT-4 to Claude, the underlying architecture remains remarkably consistent.

## Self-Attention Mechanism

The core of the transformer is the **scaled dot-product attention**. It allows the model to weigh the importance of different words in a sentence regardless of their distance.

\`\`\`python
def scaled_dot_product_attention(q, k, v, mask):
    matmul_qk = tf.matmul(q, k, transpose_b=True)
    dk = tf.cast(tf.shape(k)[-1], tf.float32)
    scaled_attention_logits = matmul_qk / tf.math.sqrt(dk)
    # ...
    return output, attention_weights
\`\`\`

## Why it works
Unlike RNNs, transformers can be parallelized, allowing us to train on massive datasets.

> "Attention is all you need." - Vaswani et al. (2017)

### Current Status
I'm currently experimenting with sparse attention mechanisms to reduce memory overhead for long-context windows.
    `,
    tags: ["research", "nlp", "transformers"],
    status: "learning",
    reading_time: 8,
    featured: true,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 2).toISOString()
  },
  {
    title: "Building a Real-time Object Detection Pipeline",
    slug: "real-time-object-detection",
    summary: "How I optimized YOLOv8 for edge devices using TensorRT and custom quantization.",
    content: `
# Optimization for the Edge

Deploying deep learning models on edge devices like the Jetson Nano requires aggressive optimization.

## The Pipeline
1. **Model Training**: YOLOv8 on custom dataset.
2. **Export**: Convert to ONNX.
3. **Quantization**: INT8 quantization using TensorRT.

### Results
We achieved a **3x speedup** in inference time with only a 1.2% drop in mAP.

| Device | FP32 (ms) | INT8 (ms) | Speedup |
|--------|-----------|-----------|---------|
| CPU    | 120       | 45        | 2.6x    |
| GPU    | 12        | 4         | 3.0x    |

## Challenges
The main challenge was handling the dynamic range of weights during quantization.
    `,
    tags: ["engineering", "computer-vision", "optimization"],
    status: "success",
    reading_time: 5,
    featured: false,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 5).toISOString()
  },
  {
    title: "Failed Experiment: Training LLMs on Synthetic Data Only",
    slug: "failed-synthetic-data-experiment",
    summary: "A post-mortem on why training exclusively on synthetic data led to catastrophic model collapse.",
    content: `
# Catastrophic Model Collapse

I tried to train a small 125M parameter model using only data generated by GPT-4. It didn't go well.

## The Hypothesis
If GPT-4 is "good enough", its output should be high-quality enough to train smaller models.

## What Happened
After 3 epochs, the model started repeating high-frequency phrases and lost all structural diversity. This is a classic case of **model collapse**.

### Lessons Learned
1. Real-world data provides the "grounding" that synthetic data lacks.
2. Diversity in the training set is more important than pure quality.

## Next Steps
I'm looking into "hybrid" training sets where synthetic data is used for data augmentation rather than the primary source.
    `,
    tags: ["experiment", "llm", "failures"],
    status: "failed",
    reading_time: 6,
    featured: false,
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 10).toISOString()
  }
];

export async function seedDatabase() {
  const path = 'posts';
  try {
    const postsRef = collection(db, path);
    const snapshot = await getDocs(postsRef);
    
    if (snapshot.empty) {
      console.log('Seeding database with initial posts...');
      for (const post of INITIAL_POSTS) {
        await addDoc(postsRef, post);
      }
      console.log('Seeding complete.');
    }
  } catch (error: any) {
    if (error.message?.includes('permission') || error.message?.includes('insufficient')) {
      console.warn('Initial seeding skipped: Missing permissions. Log in as admin to seed data.');
    } else {
      handleFirestoreError(error, OperationType.WRITE, path);
    }
  }
}
